export const PUNCHLINES = {
  bidPlaced: [
    "The throne room doors just got kicked open.",
    "Another degen with a dream and a wallet. Beautiful.",
    "The crown doesn't care about your feelings. It cares about your tokens.",
    "Someone woke up and chose ambition. Questionable ambition, but ambition.",
    "A new challenger approaches! The previous one is coping.",
    "The throne's getting expensive. So is everyone's ego.",
    "Plot twist: someone actually wants to be king. How original.",
    "Another bid, another broken dream for the previous candidate.",
    "The bidding war heats up. Your popcorn should too.",
    "Wallets are opening. Common sense is closing.",
    "Bold move. Let's see if their wallet matches their audacity.",
    "The throne just got more expensive. Your ambition should adjust accordingly.",
    "In the game of bids, you outbid or you cope. There is no middle ground.",
    "Someone just told the current candidate: 'hold my tokens.'",
    "The crown has a new suitor. The old one is now a footnote.",
  ],

  kingElected: [
    "Long live the king! Or at least until someone gets bored.",
    "A new ruler ascends! The kingdom's WiFi password remains unchanged.",
    "Bow before your new king! Or don't. He can't enforce anything yet.",
    "The people didn't vote for this. There was no vote. This is a monarchy.",
    "A king is born! His first royal decree: 'where's my treasury?'",
    "The crown fits. The responsibility? Not so much.",
    "New king, same problems. But now with more tokens!",
    "The throne is warm. The crown is heavy. The treasury is fat. Worth it.",
    "All hail the new ruler! His qualifications: outbidding everyone else.",
    "A new era begins! It'll probably end with swords. They always do.",
    "The coronation is complete. The assassination plots begin now.",
    "Congratulations to the new king! Your enemies are already sharpening their swords.",
    "From peasant to royalty in one transaction. Blockchain speed monarchy.",
    "The king is dead. Long live the king. Wait, no one died. Yet.",
    "A new butt sits upon the golden chair. The kingdom holds its breath.",
  ],

  battleStarted: [
    "The drums of war echo across the realm! Someone's feeling spicy.",
    "Peace was overrated anyway. Let the chaos begin!",
    "The king's nap has been interrupted. Violently.",
    "War has been declared! The king's therapist will be busy.",
    "Someone brought an army to a throne fight. Respect.",
    "The era of peace lasted exactly as long as everyone expected. Not long.",
    "Swords are drawn, soldiers are marching, and the king is panic-Googling 'how to fight.'",
    "The attack begins! The king's spa day is officially cancelled.",
    "Revolution is in the air. And by air, we mean the blockchain.",
    "Someone just ruined a perfectly good monarchy. The kingdom thanks them.",
    "A brave soul has challenged the crown! Or a reckless one. Same thing, really.",
    "The king was just getting comfortable. Not anymore.",
    "And just like that, the kingdom is no longer boring.",
    "War! What is it good for? Burning tokens, apparently.",
    "The first sword has been drawn. The king's confidence has been sheathed.",
  ],

  attack: [
    "More soldiers march toward the throne! The king's anxiety is doing numbers.",
    "The attack intensifies! The king is rethinking his career choices.",
    "Reinforcements! The attackers aren't playing games. Well, they are. This one.",
    "Another wave of soldiers! The king's defense budget just got a reality check.",
    "The army grows! So does the king's blood pressure.",
    "More troops deployed! The king's crown is wobbling.",
    "The attackers double down! Commitment to chaos: 10/10.",
    "Soldiers incoming! The king's shields are starting to sweat.",
    "The assault continues! Somebody really wants that king gone.",
    "More steel on the battlefield! The throne room is getting crowded.",
    "The attackers keep coming! The king's 'everything is fine' face is cracking.",
    "Another charge! At this rate, the king's going to need a bigger army. Or a running head start.",
    "Reinforcements arrive on the attack side! The king's memoir just got a dramatic chapter.",
    "The rebel army swells! The crown is feeling less secure by the minute.",
    "More soldiers! The king is updating his resume just in case.",
  ],

  defense: [
    "Defenders rally to the king! Loyalty is alive. Financial wisdom? Debatable.",
    "The king has friends! Unpaid friends, but friends nonetheless.",
    "Shields up! Someone actually believes in this king. Touching, really.",
    "Defenders assemble! The king promises to remember this. He won't.",
    "Reinforcements for the crown! The king's ego just inflated by 200%.",
    "The defense strengthens! The attackers just got a reality check.",
    "More shields! Someone is simping for the king and we're here for it.",
    "Loyal soldiers rush to the king's aid! Their wallets cry in the background.",
    "The defense line grows! The king didn't even have to ask. He expected it.",
    "Defenders incoming! The king is nodding approvingly from behind his human shield wall.",
    "Another wave of loyal subjects! The king's 'I'm fine' face just became genuine.",
    "The shield wall thickens! Attackers are going to need bigger swords.",
    "Defenders report for duty! Payment: zero. Satisfaction: also zero. But the king vibes.",
    "More soldiers for the crown! Defending royalty: the OG unpaid internship.",
    "The defense rallies! The king is already planning the after-party. You're not invited.",
  ],

  kingSurvives: [
    "The king stands! His enemies kneel. Or at least they cope.",
    "Still on the throne! Still collecting tokens! Still untouchable! For now.",
    "The crown stays put! The attackers' dreams don't.",
    "The kingdom prevails! The king's smug meter just broke.",
    "War is over! The king won! He'll be insufferable about it.",
    "The defense held! The king is already planning his victory tweet.",
    "Another battle survived! The king's ego enters orbit.",
    "The throne stands firm! The attacker's tokens do not.",
    "The king emerges victorious! His humility does not emerge at all.",
    "Battle won! The king's crown polishing intensifies.",
    "The defenders earned nothing! The king earned everything! Monarchy!",
    "The dust settles and the crown still shines. The king is unbearable.",
    "Congratulations to the king for surviving! And to the defenders for... being there.",
    "The attack failed! The king's victory dance is exactly as cringe as you'd imagine.",
    "Long live the king! The attackers' tokens? Not so long-lived.",
  ],

  kingDefeated: [
    "THE KING IS DEAD! Well, dethroned. Same energy.",
    "Down goes the crown! Down go the tokens! Down goes the ego!",
    "From royalty to peasant in one battle. Speed run completed.",
    "The mighty have fallen! And by 'mighty' we mean 'the guy who outbid everyone.'",
    "Dethroned! The ex-king's LinkedIn just updated to 'Open to Work.'",
    "The crown hits the floor! The kingdom enters its villain arc.",
    "Another king bites the dust. The throne room needs a revolving door.",
    "Regime change achieved! The revolution will be on-chain.",
    "The king is gone! His tokens are burned! His pride is unsalvageable!",
    "Fallen! The throne is empty and the former king is touching grass involuntarily.",
    "The kingdom is free! From one ruler. Until the next degen bids.",
    "Dethroned and defunded. The ex-king's memoir will be titled 'What Happened.'",
    "The crown falls! The attackers celebrate! The Alchemist feasts on burned tokens!",
    "And just like that, another king enters the history books. The footnotes section.",
    "The king has left the building. The throne has left the chat. The tokens have left existence.",
  ],
  kingStatus: [
    "The king sleeps. The kingdom watches. The blockchain remembers.",
    "Daily crown check: still on the same head. For now.",
    "Your regularly scheduled monarchy update. You're welcome.",
    "The throne is occupied. The king is... doing king things, presumably.",
    "Another day, another king still reigning. How boring. Or is it?",
    "Crown status: attached. Kingdom status: existing. Vibes: royal.",
    "The king woke up and chose to still be king. Bold strategy.",
    "24 hours later and the crown hasn't changed heads. Unprecedented stability.",
    "This is your daily reminder that someone is still king. Act accordingly.",
    "The throne report is in. The king is still there. The people are still coping.",
    "Checking in on the monarchy... yep, still a monarchy.",
    "The crown remains. The kingdom endures. The bot reports. Circle of life.",
    "Status update: the king hasn't been overthrown. Yet. The day is young.",
    "Hourly vibe check on the throne: occupied. Suspiciously occupied.",
    "The kingdom's daily newspaper has one headline: same king, different day.",
  ],

  noKing: [
    "The throne sits empty. The kingdom waits. Someone grab their wallet.",
    "No king detected. The crown gathers dust. Opportunity knocks.",
    "The throne is vacant. This is not a drill. This IS a degen signal.",
    "Crown status: available. Kingdom status: anarchy. Vibes: chaotic.",
    "There is no king. The throne is cold. Your moment is now.",
    "Daily throne check: EMPTY. Someone with tokens and no common sense, step up.",
    "The kingdom is kingless. The throne echoes with silence and untapped potential.",
    "No ruler sits upon the throne. The kingdom runs on vibes alone.",
    "Throne vacancy detected. No experience required. Just tokens and audacity.",
    "The crown lies on the ground. The kingdom holds a collective breath.",
  ],
} as const;

export function randomPunchline(
  category: keyof typeof PUNCHLINES
): string {
  const lines = PUNCHLINES[category];
  return lines[Math.floor(Math.random() * lines.length)];
}
